### ISSUE TITLE
svg-generator doesn't work

### ISSUE THREAD

**Issue by MarcinHenzel** [ngneat/svg-icon#101]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[] Other... Please describe:
</code></pre>

## Current behavior

While genereting `svg-generator` I get this:
`TypeError: (0 , svgo_1.optimize) is not a function
    at createTree (...\node_modules\@ngneat\svg-generator\tree.js:49:53)
    at createTree (...\node_modules\@ngneat\svg-generator\tree.js:25:30)
    at generateSVGIcons (...\node_modules\@ngneat\svg-generator\generator.js:19:47)
    at Object.<anonymous> (...\node_modules\@ngneat\svg-generator\index.js:9:34)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47`

and ofc ts files are not generated. 
## Expected behavior

Ts files should be generated

## Environment

 "@angular/animations": "~13.2.5",
    "@angular/cdk": "^13.2.5",
    "@angular/common": "~13.2.5",
    "@angular/compiler": "~13.2.5",
    "@angular/core": "~13.2.5",
    "@angular/forms": "~13.2.5",
    "@angular/material": "^13.2.5",
    "@angular/platform-browser": "~13.2.5",
    "@angular/platform-browser-dynamic": "~13.2.5",
    "@angular/router": "~13.2.5",
    "@ngneat/svg-icon": "^4.1.0",
It also happened on old svg-icon version when angular 13.2.5 was newest so changing version didn't change anything

 
For Tooling issues:
- Node version: 14.17.3
- Platform:  Windows

Others:
npm list @ngneat/svg-icon doesn't provide any information, but it looks like svgo is not recognized.

**Comment by NetanelBasal** [comment]
What is your svgo version?

**Comment by MarcinHenzel** [comment]
I was usign 2.8.0, but also tried 3.0.0 and 1.3.2 - same result.
My svgo config is very basic:
` "svgGenerator": {
    "outputPath": "./src/app/svg",
    "prefix": "app",
    "srcPath": "./src/assets/svg",
    "svgoConfig": {
      "plugins": [
        {
          "removeDimensions": true,
          "cleanupAttrs": true
        }
      ]
    }
  }`

**Comment by NetanelBasal** [comment]
I can't reproduce it. See if it happens on a new project, please.
