### ISSUE TITLE
Plugin name should be specified

### ISSUE THREAD

**Issue by danielehrhardt** [ngneat/svg-icon#53]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
yarn run v1.22.11
$ svg-generator
C:\Projekte\web-app\node_modules\svgo\lib\svgo\config.js:113
      throw Error(`Plugin name should be specified`);
      ^

Error: Plugin name should be specified
    at resolvePluginConfig (C:\Projekte\web-app\node_modules\svgo\lib\svgo\config.js:113:13)
    at Array.map (<anonymous>)
    at Object.optimize (C:\Projekte\web-app\node_modules\svgo\lib\svgo.js:45:37)
    at Object.createTree (C:\Projekte\web-app\node_modules\@ngneat\svg-generator\tree.js:49:40)
    at Object.generateSVGIcons (C:\Projekte\web-app\node_modules\@ngneat\svg-generator\generator.js:19:32)
    at Object.<anonymous> (C:\Projekte\web-app\node_modules\@ngneat\svg-generator\index.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.17.0
- Platform:  windows

Others:

</code></pre>

**Comment by danielehrhardt** [comment]
Somehow, it does work now.

**Comment by FrEaKmAn** [comment]
I have same issue, running `npx @ngneat/svg-generator@latest svg-generator` outputs `Plugin name should be specified`
